mobycity/carpooling/urls.py
from django.conf.urls import patterns, url

from carpooling import views


urlpatterns = patterns(
    '',
    url(r'^offer/', views.offer, name='offer'),
    url(r'^search/', views.search, name='search'),
    url(r'^search-result/', views.search_result, name='search-result'),
    url(r'^subscribe/', views.subscribe, name='subscribe'),
    url(r'^user-list-offers/', views.user_list_offers, name='user-list-offers'),
    url(r'^user-cancel-carpool/', views.user_cancel_carpool, name='user-cancel-carpool'),
    url(r'^user-list-subscriptions/', views.user_list_subscriptions, name='user-list-subscriptions'),
    url(r'^user-cancel-subscription/', views.user_cancel_subscription, name='user-cancel-subscription'),
    url(r'^user-accept-or-deny-subscription/', views.user_accept_or_deny_subscription, name='user-accept-or-deny-subscription'),
    url(r'^$', views.search, name='search'),
)

mobycity/mobycity/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls import patterns
from django.conf.urls.static import static
from django.contrib import admin

# admin.autodiscover() # Not required for Django 1.7.x+

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mobycity.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^news/', include('news.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^cartography/', include('cartography.urls')),
    url(r'^carpooling/', include('carpooling.urls')),
    url(r'^profile/', include('user_profile.urls')),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mobycity/news/urls.py
from django.conf.urls import patterns, url

from news import views


urlpatterns = patterns(
    '',
    url(r'^list/', views.list, name='list'),
    url(r'^$', views.list, name='list'),
)

mobycity/carpooling/models.py
#coding:utf-8

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


lat_1km = 0.008
lng_1km = 0.012


class Carpool(models.Model):
    creation_datetime = models.DateTimeField(blank=True, default=timezone.now, verbose_name=u'Date de création')
    update_datetime = models.DateTimeField(blank=True, default=timezone.now, verbose_name=u'Date de mise à jour')

    organizer = models.ForeignKey(User)

    departure_latitude = models.FloatField(verbose_name=u'Départ - latitude')
    departure_longitude = models.FloatField(verbose_name=u'Départ - longitude')
    arrival_latitude = models.FloatField(verbose_name=u'Arrivée - latitude')
    arrival_longitude = models.FloatField(verbose_name=u'Arrivée - longitude')

    FREQUENCY_CHOICES = (
        ('OCC', u'Ponctuel'),
        ('REG', u'Régulier'),
    )
    frequency = models.CharField(max_length=3, choices=FREQUENCY_CHOICES, default='OCC', verbose_name=u'Fréquence')

    occ_departure_datetime = models.DateTimeField(null=True, blank=True, verbose_name=u'Date de départ')
    occ_arrival_datetime = models.DateTimeField(null=True, blank=True, verbose_name=u'Date d\'arrivée')
    
    reg_departure_time = models.TimeField(null=True, blank=True, verbose_name=u'Heure de départ')
    reg_arrival_time = models.TimeField(null=True, blank=True, verbose_name=u'Heure d\'arrivée')

    SEATS_NUMBER_CHOICES = [(i,i) for i in range(1, 11)]
    SEATS_NUMBER_CHOICES.append((None, u'Places disponibles'))
    seats_number = models.PositiveSmallIntegerField(max_length=10, choices=SEATS_NUMBER_CHOICES, verbose_name=u'Places disponibles')
    
    free = models.BooleanField(default=True, verbose_name=u'Covoiturage gratuit')
    comment = models.TextField(blank=True, verbose_name=u'Commentaire')
    cancelled = models.BooleanField(default=False, verbose_name=u'Annulé')

    class Meta:
        verbose_name = u'Covoiturage'
        verbose_name_plural = u'Covoiturages'

    def __unicode__(self):
        return '%d' % self.id

class Subscription(models.Model):
    creation_datetime = models.DateTimeField(blank=True, default=timezone.now, verbose_name=u'Date de création')
    update_datetime = models.DateTimeField(blank=True, default=timezone.now, verbose_name=u'Date de mise à jour')

    subscriber = models.ForeignKey(User, verbose_name=u'Inscrit')
    carpool = models.ForeignKey(Carpool, verbose_name=u'Covoiturage')

    cancelled = models.BooleanField(default=False, verbose_name=u'Annulée')
    accepted = models.NullBooleanField(default=None, verbose_name=u'Acceptée')

    class Meta:
        verbose_name = u'Inscription'
        verbose_name_plural = u'Inscriptions'

    def __unicode__(self):
        return '%d' % self.id

mobycity/carpooling/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core import serializers
from django.utils import timezone
from django.db import connection
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.conf import settings
from datetime import date, datetime, timedelta
from allauth.account.decorators import verified_email_required

from carpooling.forms import OfferCarpoolForm, SearchCarpoolForm
from carpooling.models import Carpool, Subscription, lat_1km, lng_1km
from cartography.models import Category, PointOfInterest


# Marges pour la recherche
search_timedelta = timedelta(minutes=15)
search_lat_delta = lat_1km
search_lng_delta = lng_1km


@verified_email_required
def offer(request):
    form = OfferCarpoolForm(request.POST or None, initial={'occ_departure_datetime': timezone.now, 'occ_arrival_datetime': timezone.now, 'reg_departure_time': timezone.now, 'reg_arrival_time': timezone.now})

    # cartography
    category_list_json = serializers.serialize('json', Category.objects.all())
    point_of_interest_list_json = serializers.serialize('json', PointOfInterest.objects.all())

    context = {
        'form': form,

        # cartography
        'category_list_json': category_list_json,
        'point_of_interest_list_json': point_of_interest_list_json,
    }

    if request.method == 'POST':
        if form.is_valid():
            carpool = form.save(commit=False)
            carpool.organizer = request.user
            carpool.save()
            
            messages.success(request, u'Votre offre de covoiturage a été publiée.')
            return HttpResponseRedirect('')
        else:
            messages.error(request, 'Une erreur est survenue.')
            
    return render(request, 'carpooling/offer.html', context)


def search(request):
    form = SearchCarpoolForm(request.GET or None, initial={'occ_arrival_datetime': timezone.now, 'reg_arrival_time': timezone.now})
    
    # cartography
    category_list_json = serializers.serialize('json', Category.objects.all())
    point_of_interest_list_json = serializers.serialize('json', PointOfInterest.objects.all())

    context = {
        'form': form,

        # cartography
        'category_list_json': category_list_json,
        'point_of_interest_list_json': point_of_interest_list_json,
    }

    return render(request, 'carpooling/search.html', context)


def search_result(request):
    carpool_list = []
    subscription_carpool_list = None

    form = SearchCarpoolForm(request.GET or None, initial={'occ_arrival_datetime': timezone.now, 'reg_arrival_time': timezone.now})

    if request.GET:
        if form.is_valid():

            # Frequence selectionnee
            # Ordre d'affichage
            carpool_list = Carpool.objects.filter(frequency=form.cleaned_data['frequency']).order_by('-creation_datetime')
            
            # Trajet occasionnel
            if form.cleaned_data['frequency'] == 'OCC':
                # Date a venir
                carpool_list = carpool_list.filter(occ_departure_datetime__gt=timezone.now)
                
                # Autour de la date/heure recherchee
                occ_arrival_datetime_min = form.cleaned_data['occ_arrival_datetime'] - search_timedelta
                occ_arrival_datetime_max = form.cleaned_data['occ_arrival_datetime'] + search_timedelta
                
                carpool_list = carpool_list.filter(occ_arrival_datetime__range=(occ_arrival_datetime_min, occ_arrival_datetime_max))
                
            # Trajet regulier
            if form.cleaned_data['frequency'] == 'REG':
                (datetime.combine(date(1, 1, 1), form.cleaned_data['reg_arrival_time']) + search_timedelta).time()
                
                # Autour de l'heure recherchee
                reg_arrival_time_min = (datetime.combine(date(2, 2, 2), form.cleaned_data['reg_arrival_time']) - search_timedelta).time()
                reg_arrival_time_max = (datetime.combine(date(2, 2, 2), form.cleaned_data['reg_arrival_time']) + search_timedelta).time()
                
                print reg_arrival_time_min
                print reg_arrival_time_max
                
                # Sur 1 jour
                if reg_arrival_time_min <= reg_arrival_time_max:
                    carpool_list = carpool_list.filter(reg_arrival_time__gte=reg_arrival_time_min)
                    carpool_list = carpool_list.filter(reg_arrival_time__lte=reg_arrival_time_max)
                # Sur 2 jours
                else:
                    carpool_list = carpool_list.filter(Q(reg_arrival_time__gte=reg_arrival_time_min) | Q(reg_arrival_time__lte=reg_arrival_time_max))
            
            # Fourchette pour le point de depart
            departure_latitude_max = form.cleaned_data['departure_latitude'] - search_lat_delta
            departure_latitude_min = form.cleaned_data['departure_latitude'] + search_lat_delta
            departure_longitude_max = form.cleaned_data['departure_longitude'] - search_lng_delta
            departure_longitude_min = form.cleaned_data['departure_longitude'] + search_lng_delta

            carpool_list = carpool_list.filter(departure_latitude__range=(str(departure_latitude_max), str(departure_latitude_min)))
            carpool_list = carpool_list.filter(departure_longitude__range=(str(departure_longitude_max), str(departure_longitude_min)))

            # Fourchette pour le point d'arrivee
            arrival_latitude_max = form.cleaned_data['arrival_latitude'] - search_lat_delta
            arrival_latitude_min = form.cleaned_data['arrival_latitude'] + search_lat_delta
            arrival_longitude_max = form.cleaned_data['arrival_longitude'] - search_lng_delta
            arrival_longitude_min = form.cleaned_data['arrival_longitude'] + search_lng_delta

            carpool_list = carpool_list.filter(arrival_latitude__range=(str(arrival_latitude_max), str(arrival_latitude_min)))
            carpool_list = carpool_list.filter(arrival_longitude__range=(str(arrival_longitude_max), str(arrival_longitude_min)))

            # Pas annule
            carpool_list = carpool_list.filter(cancelled=False)

            cursor = connection.cursor()

            # TODO Simplifier en une seule requete
            # Covoiturages dans lesquels il reste au moins une place
            cursor.execute('select distinct c.id '
                           'from carpooling_carpool c '
                           'where c.seats_number > '
                           '        (select count (*) '
                           '        from carpooling_subscription s '
                           '        where s.carpool_id = c.id'
                           '        and s.accepted <> true)'
                           'order by c.id ASC;')

            available_carpool_list = cursor.fetchall()
            available_carpool_id_list = [i[0] for i in available_carpool_list]

            carpool_list = carpool_list.filter(id__in=available_carpool_id_list)

            # Pagination
            paginator = Paginator(carpool_list, 10)
            page = request.GET.get('page')
            
            try:
                carpool_paginated_list = paginator.page(page)
            except PageNotAnInteger:
                # If page is not an integer, deliver first page.
                carpool_paginated_list = paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999), deliver last page of results.
                carpool_paginated_list = paginator.page(paginator.num_pages)

            # Liste des inscriptions de l'utilisateur
            if not request.user.is_anonymous():
                subscription_carpool_list = Subscription.objects.values_list('carpool').filter(subscriber=request.user)
                
        else:
            messages.error(request, u'Une erreur est survenue.')
            return HttpResponseRedirect('/carpooling/search')

    else: 
        return HttpResponseRedirect('/carpooling/search')
    
    carpool_list_json = serializers.serialize('json', carpool_list, fields=('departure_latitude', 'departure_longitude', 'arrival_latitude', 'arrival_longitude'))

    # cartography
    category_list_json = serializers.serialize('json', Category.objects.all())
    point_of_interest_list_json = serializers.serialize('json', PointOfInterest.objects.all())

    context = {
        'form': form,
        'carpool_list': carpool_paginated_list,
        'carpool_list_json': carpool_list_json,
        'subscription_carpool_list': subscription_carpool_list,

        # cartography
        'category_list_json': category_list_json,
        'point_of_interest_list_json': point_of_interest_list_json,
    }
    
    return render(request, 'carpooling/search_result.html', context)


@verified_email_required
def subscribe(request):
    if request.method == 'POST' and 'carpool_id' in request.POST:
        carpool = Carpool.objects.get(pk=request.POST['carpool_id'])
        accepted_subscription_count = Subscription.objects.filter(carpool=carpool, accepted=True).count()

        # L'inscrit ne peut etre l'organisateur du covoiturage
        # Il doit y avoir suffisamment de place disponible
        # Le covoiturage ne doit pas etre annule
        # La date de depart ne doit pas etre depassee
        if carpool.organizer != request.user and accepted_subscription_count < carpool.seats_number and not carpool.cancelled and (carpool.frequency == 'REG' or (carpool.frequency == 'OCC' and carpool.occ_departure_datetime >= timezone.now())):
            # Deja inscrit pour ce covoiturage
            try:
                Subscription.objects.get(subscriber=request.user, carpool=carpool)

            # Inscription a ce covoiturage

mobycity/templates/carpooling/offer.html
{% extends "mobycity/base.html" %}
{% load cms_tags sekizai_tags %}
{% load bootstrap3 %}
{% load static %}

{% block content %}
    {% addtoblock "js" %}
        <script type="text/javascript">
            var categoryList = {{ category_list_json | safe }};
            var pointOfInterestList = {{ point_of_interest_list_json | safe }};

            var mediaBaseUrl = '{% get_media_prefix %}';
            
            var centerLat = 45.759723;
            var centerLng = 4.842223;
            
            var boundBottomLeftLat = 45.707146;
            var boundBottomLeftLng = 4.768516;
            var boundTopRightLat = 45.809187;
            var boundTopRightLng = 4.895545;
            
            var mapStyles = [{'featureType':'landscape','elementType':'all','stylers':[{'color':'#a8a8a8'},{'gamma':'9.69'}]},{'featureType':'poi','elementType':'all','stylers':[{'hue':'#b5ff00'},{'saturation':33.4},{'lightness':-25.4},{'gamma':1}]},{'featureType':'road.highway','elementType':'all','stylers':[{'hue':'#b5ff00'},{'saturation':-73},{'lightness':40},{'gamma':1}]},{'featureType':'road.arterial','elementType':'all','stylers':[{'hue':'#ffcc00'},{'gamma':1}]},{'featureType':'road.local','elementType':'all','stylers':[{'hue':'#00c0ff'},{'lightness':30},{'gamma':1}]},{'featureType':'water','elementType':'all','stylers':[{'hue':'#008aff'},{'saturation':6},{'lightness':8},{'gamma':1}]},{'featureType':'administrative','elementType':'all','stylers':[{'hue':'#8c8c8c'},{'saturation':0},{'lightness':0},{'gamma':1}]}];
            
            var markerIconA = '{% static "mobycity/images/cartographie-depart.png" %}';
            var markerIconB = '{% static "mobycity/images/cartographie-arrivee.png" %}';
            
            var markerLabelA = '';
            var markerLabelB = '';
        </script>
    {% endaddtoblock %}

    <div class="covoiturage">
        <div class="slider">
            <div class="container">
                <h1>Covoiturage</h1>
            </div>
        </div>

        <div id="onglets" class="container">
            <ul class="list-inline col-md-12">
                <li class="col-md-2 col-md-offset-4"><a href="/covoiturage">Rechercher</a></li>
                <li class="col-md-2 active"><a href="/covoiturage/offer">Proposer</a></li>
            </ul>
        </div>
        
        <div id="corps" class="container">
            <div class="bloc-titre">
                <h2>Proposer un covoiturage</h2>
                <p class="consigne">Indiquez vos points de départ et d'arrivée en les déplaçant sur la carte</p>
            </div>
            <div id="covoiturage-offrir">
                <form action="./" method="post">
                    <div class="row">
                        <div class="col-md-6">
                            {% bootstrap_form_errors form %}
                            {% csrf_token %}
                            {% bootstrap_field form.departure_latitude %}
                            {% bootstrap_field form.departure_longitude %}
                            {% bootstrap_field form.arrival_latitude %}
                            {% bootstrap_field form.arrival_longitude %}

                            <div class="covoiturage-offrir-row row">
                                <div id="covoiturage-offrir-type-trajet" class="col-sm-6">
                                    <ul class="list-inline">
                                        {% for radio in form.frequency %}
                                            <li class="list-inline">
                                                {{ radio.tag }}
                                                <label for="{{ radio.id_for_label }}">
                                                    {{ radio.choice_label }}
                                                </label>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    {% bootstrap_field form.seats_number show_label=False field_class='form-select' %}
                                </div>
                            </div>
                            <div id="occ" class="form-inline">
                                <div class="covoiturage-offrir-row row">
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <div id="covoiturage-offrir-depart">
                                                <span>Départ</span>
                                            </div>
                                        </div>
                                        <div class="col-sm-9">
                                            {% bootstrap_field form.occ_departure_datetime show_label=False field_class='form-datetime' %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <div id="covoiturage-offrir-arrivee">
                                                <span>Arrivée</span>
                                            </div>
                                        </div>
                                        <div class="col-sm-9">
                                            {% bootstrap_field form.occ_arrival_datetime show_label=False field_class='form-datetime' %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div id="reg" class="form-inline">
                                <div class="covoiturage-offrir-row row">
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <div id="covoiturage-offrir-depart">
                                                <span>Départ</span>
                                            </div>
                                        </div>
                                        <div class="col-sm-9">
                                            {% bootstrap_field form.reg_departure_time show_label=False field_class='form-time' %}
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <div id="covoiturage-offrir-arrivee">
                                                <span>Arrivée</span>
                                            </div>
                                        </div>
                                        <div class="col-sm-9">
                                            {% bootstrap_field form.reg_arrival_time show_label=False field_class='form-time' %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="covoiturage-offrir-row row">
                                <div id="covoiturage-offrir-gratuit" class="col-xs-12">
                                    {{ form.free }} <label for="id_free">Proposer le trajet gratuitement</label>
                                </div>
                            </div>
                            <div class="covoiturage-offrir-row row">
                                <div class="col-xs-12">
                                    {% bootstrap_field form.comment %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="cartographie-map-container embed-responsive embed-responsive-square">
                                {% include 'cartography/map.html' %}
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-12 text-center v-gap-30">
                            <input type="submit" value="Poster mon annonce" class="btn" />
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    {% addtoblock "js" %}
        <script type="text/javascript" src="{% static 'carpooling/js/offer-search.js' %}"></script>
    {% endaddtoblock %}
    
    {#********** DATE **********#}
    {% addtoblock "css" %}
        <link href="{% static 'mobycity/js/bootstrap-datepicker-1.5.0-dist/css/bootstrap-datepicker3.min.css' %}" media="screen, projection" rel="stylesheet" type="text/css" />
    {% endaddtoblock %}
    {% addtoblock "js" %}
        <script type="text/javascript" src="{% static 'mobycity/js/bootstrap-datepicker-1.5.0-dist/js/bootstrap-datepicker.min.js' %}"></script>
    {% endaddtoblock %}
    {% addtoblock "js" %}
        <script type="text/javascript" src="{% static 'mobycity/js/bootstrap-datepicker-1.5.0-dist/locales/bootstrap-datepicker.fr.min.js' %}" charset="UTF-8"></script>
    {% endaddtoblock %}
    {% addtoblock "js" %}
        <script>
            $('#id_occ_departure_datetime_0').datepicker({
                format: "dd/mm/yyyy",
                weekStart: 1,
                todayBtn: "linked",
                language: "fr",
                autoclose: true,
                maxViewMode: 0
            }).on('show', function(e) {
                
            });
            
            $('#id_occ_arrival_datetime_0').datepicker({
                format: "dd/mm/yyyy",
                weekStart: 1,
                todayBtn: "linked",
                language: "fr",
                autoclose: true,
                maxViewMode: 0
            }).on('show', function(e) {
                
            });
        </script>
    {% endaddtoblock %}
    
    {#********** HEURE **********#}
    {% addtoblock "css" %}
        <link href="{% static 'mobycity/js/bootstrap-timepicker-0.5.1/css/bootstrap-timepicker.min.css' %}" media="screen, projection" rel="stylesheet" type="text/css" />
    {% endaddtoblock %}
    {% addtoblock "js" %}
        <script type="text/javascript" src="{% static 'mobycity/js/bootstrap-timepicker-0.5.1/js/bootstrap-timepicker.min.js' %}"></script>
    {% endaddtoblock %}
    {% addtoblock "js" %}
        <script>
            $('#id_occ_departure_datetime_1').timepicker({
                showMeridian: false                
            });
            
            $('#id_reg_departure_time').timepicker({
                showMeridian: false
            });
            
            $('#id_occ_arrival_datetime_1').timepicker({
                showMeridian: false                
            });
            
            $('#id_reg_arrival_time').timepicker({
                showMeridian: false
            });
        </script>
    {% endaddtoblock %}
{% endblock %}